# Form implementation generated from reading ui file 'Form_Inicio.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Inicio(object):
    def setupUi(self, Form_Inicio):
        Form_Inicio.setObjectName("Form_Inicio")
        Form_Inicio.resize(1463, 934)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/sistemablue.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_Inicio.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=Form_Inicio)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_35.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_35.setSpacing(0)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.frame_lateral = QtWidgets.QFrame(parent=self.frame)
        self.frame_lateral.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.frame_lateral.setFont(font)
        self.frame_lateral.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.518552, y1:0.414227, x2:0.52957, y2:1, stop:0 #000046 , stop:1 #1CB5E0);\n"
"")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_13.setContentsMargins(5, 5, 5, 0)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Bt_Inicio = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Inicio.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Inicio.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Inicio.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/inicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Inicio.setIcon(icon1)
        self.Bt_Inicio.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Inicio.setShortcut("")
        self.Bt_Inicio.setCheckable(False)
        self.Bt_Inicio.setAutoRepeat(False)
        self.Bt_Inicio.setAutoExclusive(False)
        self.Bt_Inicio.setAutoDefault(False)
        self.Bt_Inicio.setDefault(False)
        self.Bt_Inicio.setFlat(False)
        self.Bt_Inicio.setObjectName("Bt_Inicio")
        self.verticalLayout_13.addWidget(self.Bt_Inicio)
        self.Bt_Atendimento = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Atendimento.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Atendimento.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Atendimento.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/4647605.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Atendimento.setIcon(icon2)
        self.Bt_Atendimento.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Atendimento.setShortcut("")
        self.Bt_Atendimento.setCheckable(False)
        self.Bt_Atendimento.setAutoRepeat(False)
        self.Bt_Atendimento.setAutoExclusive(False)
        self.Bt_Atendimento.setAutoDefault(False)
        self.Bt_Atendimento.setDefault(False)
        self.Bt_Atendimento.setFlat(False)
        self.Bt_Atendimento.setObjectName("Bt_Atendimento")
        self.verticalLayout_13.addWidget(self.Bt_Atendimento)
        self.Bt_Clientes = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Clientes.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Clientes.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Clientes.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/clientes.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Clientes.setIcon(icon3)
        self.Bt_Clientes.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Clientes.setShortcut("")
        self.Bt_Clientes.setCheckable(False)
        self.Bt_Clientes.setAutoRepeat(False)
        self.Bt_Clientes.setAutoExclusive(False)
        self.Bt_Clientes.setAutoDefault(False)
        self.Bt_Clientes.setDefault(False)
        self.Bt_Clientes.setFlat(False)
        self.Bt_Clientes.setObjectName("Bt_Clientes")
        self.verticalLayout_13.addWidget(self.Bt_Clientes)
        self.Bt_Usuarios = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Usuarios.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Usuarios.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Usuarios.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/adduser_.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Usuarios.setIcon(icon4)
        self.Bt_Usuarios.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Usuarios.setShortcut("")
        self.Bt_Usuarios.setCheckable(False)
        self.Bt_Usuarios.setAutoRepeat(False)
        self.Bt_Usuarios.setAutoExclusive(False)
        self.Bt_Usuarios.setAutoDefault(False)
        self.Bt_Usuarios.setDefault(False)
        self.Bt_Usuarios.setFlat(False)
        self.Bt_Usuarios.setObjectName("Bt_Usuarios")
        self.verticalLayout_13.addWidget(self.Bt_Usuarios)
        self.Bt_Suporte = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Suporte.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Suporte.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Suporte.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/Suporte copiar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Suporte.setIcon(icon5)
        self.Bt_Suporte.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Suporte.setShortcut("")
        self.Bt_Suporte.setCheckable(False)
        self.Bt_Suporte.setAutoRepeat(False)
        self.Bt_Suporte.setAutoExclusive(False)
        self.Bt_Suporte.setAutoDefault(False)
        self.Bt_Suporte.setDefault(False)
        self.Bt_Suporte.setFlat(False)
        self.Bt_Suporte.setObjectName("Bt_Suporte")
        self.verticalLayout_13.addWidget(self.Bt_Suporte)
        self.Bt_Sair = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.Bt_Sair.setMinimumSize(QtCore.QSize(0, 30))
        self.Bt_Sair.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Bt_Sair.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);;\n"
"font: 8pt \"MS Shell Dlg 2\";\n"
"font-size:12px;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(157, 157, 157);\n"
"}")
        self.Bt_Sair.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/sair.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Sair.setIcon(icon6)
        self.Bt_Sair.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Sair.setShortcut("")
        self.Bt_Sair.setCheckable(False)
        self.Bt_Sair.setAutoRepeat(False)
        self.Bt_Sair.setAutoExclusive(False)
        self.Bt_Sair.setAutoDefault(False)
        self.Bt_Sair.setDefault(False)
        self.Bt_Sair.setFlat(False)
        self.Bt_Sair.setObjectName("Bt_Sair")
        self.verticalLayout_13.addWidget(self.Bt_Sair)
        spacerItem = QtWidgets.QSpacerItem(20, 221, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.label_23 = QtWidgets.QLabel(parent=self.frame_lateral)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:1CB5E0;")
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_13.addWidget(self.label_23)
        self.gridLayout_35.addWidget(self.frame_lateral, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.inicio = QtWidgets.QWidget()
        self.inicio.setObjectName("inicio")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.inicio)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_5 = QtWidgets.QFrame(parent=self.inicio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_18 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_18.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_9.setContentsMargins(1, 0, 1, 1)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_60 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_60.setMinimumSize(QtCore.QSize(407, 0))
        self.frame_60.setMaximumSize(QtCore.QSize(401, 16777215))
        self.frame_60.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_60.setObjectName("frame_60")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_60)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setHorizontalSpacing(0)
        self.gridLayout_13.setVerticalSpacing(1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_34 = QtWidgets.QFrame(parent=self.frame_60)
        self.frame_34.setMinimumSize(QtCore.QSize(396, 0))
        self.frame_34.setStyleSheet("background-color: rgb(0, 85, 255);\n"
"")
        self.frame_34.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_34)
        self.horizontalLayout_7.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.nome_user_3 = QtWidgets.QLabel(parent=self.frame_34)
        self.nome_user_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"background-color: rgb(0, 85, 255);\n"
"")
        self.nome_user_3.setObjectName("nome_user_3")
        self.horizontalLayout_7.addWidget(self.nome_user_3)
        self.Lb_User_Logado_3 = QtWidgets.QLabel(parent=self.frame_34)
        self.Lb_User_Logado_3.setMinimumSize(QtCore.QSize(0, 0))
        self.Lb_User_Logado_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"\n"
"\n"
"\n"
"")
        self.Lb_User_Logado_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Lb_User_Logado_3.setObjectName("Lb_User_Logado_3")
        self.horizontalLayout_7.addWidget(self.Lb_User_Logado_3)
        self.gridLayout_13.addWidget(self.frame_34, 2, 0, 1, 1)
        self.frame_33 = QtWidgets.QFrame(parent=self.frame_60)
        self.frame_33.setMinimumSize(QtCore.QSize(407, 0))
        self.frame_33.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_33.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_33.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 30)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Bt_Expandir = QtWidgets.QPushButton(parent=self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Expandir.sizePolicy().hasHeightForWidth())
        self.Bt_Expandir.setSizePolicy(sizePolicy)
        self.Bt_Expandir.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Bt_Expandir.setStyleSheet("\n"
"border:none;")
        self.Bt_Expandir.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("G:/Meu Drive/PROGRAMAÇÃO/PROJETOS/MEUS PROJETOS/SISTEMA SAÚDE 11.02.2023/img/hamburg01.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Expandir.setIcon(icon7)
        self.Bt_Expandir.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Expandir.setShortcut("")
        self.Bt_Expandir.setCheckable(False)
        self.Bt_Expandir.setAutoRepeat(False)
        self.Bt_Expandir.setAutoExclusive(False)
        self.Bt_Expandir.setAutoDefault(False)
        self.Bt_Expandir.setDefault(False)
        self.Bt_Expandir.setFlat(False)
        self.Bt_Expandir.setObjectName("Bt_Expandir")
        self.horizontalLayout.addWidget(self.Bt_Expandir)
        spacerItem1 = QtWidgets.QSpacerItem(209, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Bt_Notifica = QtWidgets.QPushButton(parent=self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Notifica.sizePolicy().hasHeightForWidth())
        self.Bt_Notifica.setSizePolicy(sizePolicy)
        self.Bt_Notifica.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Bt_Notifica.setStyleSheet("\n"
"border:none;")
        self.Bt_Notifica.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("G:/Meu Drive/PROGRAMAÇÃO/PROJETOS/MEUS PROJETOS/Sistema - EM PRODUÇÃO - Copia/icones/notifica01.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Notifica.setIcon(icon8)
        self.Bt_Notifica.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Notifica.setShortcut("")
        self.Bt_Notifica.setCheckable(False)
        self.Bt_Notifica.setAutoRepeat(False)
        self.Bt_Notifica.setAutoExclusive(False)
        self.Bt_Notifica.setAutoDefault(False)
        self.Bt_Notifica.setDefault(False)
        self.Bt_Notifica.setFlat(False)
        self.Bt_Notifica.setObjectName("Bt_Notifica")
        self.horizontalLayout.addWidget(self.Bt_Notifica)
        self.Bt_Conta_notificacao = QtWidgets.QPushButton(parent=self.frame_33)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Conta_notificacao.sizePolicy().hasHeightForWidth())
        self.Bt_Conta_notificacao.setSizePolicy(sizePolicy)
        self.Bt_Conta_notificacao.setMaximumSize(QtCore.QSize(30, 16777215))
        self.Bt_Conta_notificacao.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 11pt \"MS Shell Dlg 2\";\n"
"border:none;")
        self.Bt_Conta_notificacao.setText("")
        self.Bt_Conta_notificacao.setIconSize(QtCore.QSize(25, 25))
        self.Bt_Conta_notificacao.setShortcut("")
        self.Bt_Conta_notificacao.setCheckable(False)
        self.Bt_Conta_notificacao.setAutoRepeat(False)
        self.Bt_Conta_notificacao.setAutoExclusive(False)
        self.Bt_Conta_notificacao.setAutoDefault(False)
        self.Bt_Conta_notificacao.setDefault(False)
        self.Bt_Conta_notificacao.setFlat(False)
        self.Bt_Conta_notificacao.setObjectName("Bt_Conta_notificacao")
        self.horizontalLayout.addWidget(self.Bt_Conta_notificacao)
        self.gridLayout_13.addWidget(self.frame_33, 0, 0, 1, 1)
        self.frame_32 = QtWidgets.QFrame(parent=self.frame_60)
        self.frame_32.setMinimumSize(QtCore.QSize(396, 0))
        self.frame_32.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_32.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_32.setObjectName("frame_32")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_32)
        self.horizontalLayout_13.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.nome_user_2 = QtWidgets.QLabel(parent=self.frame_32)
        self.nome_user_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"background-color: rgb(0, 85, 255);\n"
"")
        self.nome_user_2.setObjectName("nome_user_2")
        self.horizontalLayout_13.addWidget(self.nome_user_2)
        self.Lb_User_Logado_2 = QtWidgets.QLabel(parent=self.frame_32)
        self.Lb_User_Logado_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"background-color: rgb(0, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Sitka Text\";\n"
"\n"
"\n"
"\n"
"")
        self.Lb_User_Logado_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Lb_User_Logado_2.setObjectName("Lb_User_Logado_2")
        self.horizontalLayout_13.addWidget(self.Lb_User_Logado_2)
        self.gridLayout_13.addWidget(self.frame_32, 1, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_60)
        self.frame_36 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_36.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_36.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_36.setObjectName("frame_36")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_36)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setHorizontalSpacing(0)
        self.gridLayout_14.setVerticalSpacing(1)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Lb_Logo_Inicio_Topo = QtWidgets.QLabel(parent=self.frame_36)
        self.Lb_Logo_Inicio_Topo.setMinimumSize(QtCore.QSize(500, 0))
        self.Lb_Logo_Inicio_Topo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Lb_Logo_Inicio_Topo.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.Lb_Logo_Inicio_Topo.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Lb_Logo_Inicio_Topo.setText("")
        self.Lb_Logo_Inicio_Topo.setObjectName("Lb_Logo_Inicio_Topo")
        self.gridLayout_14.addWidget(self.Lb_Logo_Inicio_Topo, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_36)
        self.frame_35 = QtWidgets.QFrame(parent=self.frame_18)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_35.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_17 = QtWidgets.QFrame(parent=self.frame_35)
        self.frame_17.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(679, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_17)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.Lb_UserLogado = QtWidgets.QLabel(parent=self.frame_17)
        self.Lb_UserLogado.setMinimumSize(QtCore.QSize(150, 0))
        self.Lb_UserLogado.setStyleSheet("font: 14pt \"OCR A Extended\";\n"
"color: rgb(0, 255, 127);")
        self.Lb_UserLogado.setText("")
        self.Lb_UserLogado.setObjectName("Lb_UserLogado")
        self.gridLayout.addWidget(self.Lb_UserLogado, 0, 2, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_17)
        self.frame_37 = QtWidgets.QFrame(parent=self.frame_35)
        self.frame_37.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_37.setObjectName("frame_37")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_37)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.Lb_Logo_Inicio_Topo_3 = QtWidgets.QLabel(parent=self.frame_37)
        self.Lb_Logo_Inicio_Topo_3.setMinimumSize(QtCore.QSize(500, 0))
        self.Lb_Logo_Inicio_Topo_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Lb_Logo_Inicio_Topo_3.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.Lb_Logo_Inicio_Topo_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Lb_Logo_Inicio_Topo_3.setText("")
        self.Lb_Logo_Inicio_Topo_3.setObjectName("Lb_Logo_Inicio_Topo_3")
        self.gridLayout_11.addWidget(self.Lb_Logo_Inicio_Topo_3, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_37)
        self.horizontalLayout_9.addWidget(self.frame_35)
        self.gridLayout_10.addWidget(self.frame_18, 0, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_19.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_21.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_3.addWidget(self.frame_21)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_23.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_23.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.Lb_logo_Inicio = QtWidgets.QLabel(parent=self.frame_23)
        self.Lb_logo_Inicio.setGeometry(QtCore.QRect(1, 1, 16, 16))
        self.Lb_logo_Inicio.setText("")
        self.Lb_logo_Inicio.setObjectName("Lb_logo_Inicio")
        self.horizontalLayout_3.addWidget(self.frame_23)
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_19)
        self.frame_22.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_3.addWidget(self.frame_22)
        self.gridLayout_10.addWidget(self.frame_19, 1, 0, 1, 1)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_20.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_24.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_5.addWidget(self.frame_24)
        self.frame_25 = QtWidgets.QFrame(parent=self.frame_20)
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_25.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem3 = QtWidgets.QSpacerItem(386, 12, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(parent=self.frame_25)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(386, 12, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_5.addWidget(self.frame_25)
        self.gridLayout_10.addWidget(self.frame_20, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.inicio)
        self.atendimento = QtWidgets.QWidget()
        self.atendimento.setStyleSheet("")
        self.atendimento.setObjectName("atendimento")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.atendimento)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.atendimento)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_13.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.518552, y1:0.414227, x2:0.52957, y2:1, stop:0 #1CB5E0 , stop:1 #1CB5E0);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_15.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_15.setStyleSheet("QPushButton {\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
"\n"
"text-transform: uppercase\n"
" }\n"
"QPushButton:hover{\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"text-decoration:underline;\n"
"\n"
"\n"
"\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/suportee.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_15.setIcon(icon9)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_8.addWidget(self.pushButton_15)
        spacerItem5 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_6.addWidget(self.frame_13)
        self.groupBox = QtWidgets.QGroupBox(parent=self.frame_6)
        self.groupBox.setMinimumSize(QtCore.QSize(500, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.groupBox.setObjectName("groupBox")
        self.Tx_FiltroData = QtWidgets.QDateEdit(parent=self.groupBox)
        self.Tx_FiltroData.setGeometry(QtCore.QRect(20, 50, 141, 22))
        self.Tx_FiltroData.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 85, 255);\n"
"font: 75 8pt \"Trebuchet MS\";")
        self.Tx_FiltroData.setCalendarPopup(True)
        self.Tx_FiltroData.setObjectName("Tx_FiltroData")
        self.Lb_FiltroData = QtWidgets.QLabel(parent=self.groupBox)
        self.Lb_FiltroData.setGeometry(QtCore.QRect(20, 30, 141, 16))
        self.Lb_FiltroData.setStyleSheet("color: rgb(255, 255, 255);")
        self.Lb_FiltroData.setObjectName("Lb_FiltroData")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(350, 30, 151, 20))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.Tx_FiltroStatus = QtWidgets.QComboBox(parent=self.groupBox)
        self.Tx_FiltroStatus.setGeometry(QtCore.QRect(350, 51, 141, 21))
        self.Tx_FiltroStatus.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Trebuchet MS\";")
        self.Tx_FiltroStatus.setObjectName("Tx_FiltroStatus")
        self.Tx_FiltroStatus.addItem("")
        self.Tx_FiltroStatus.addItem("")
        self.Tx_FiltroStatus.addItem("")
        self.Tx_FiltroStatus.addItem("")
        self.Tx_FiltroStatus.addItem("")
        self.Bt_FtData = QtWidgets.QPushButton(parent=self.groupBox)
        self.Bt_FtData.setGeometry(QtCore.QRect(170, 50, 21, 20))
        self.Bt_FtData.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:50px;")
        self.Bt_FtData.setObjectName("Bt_FtData")
        self.Bt_FtStatus = QtWidgets.QPushButton(parent=self.groupBox)
        self.Bt_FtStatus.setGeometry(QtCore.QRect(500, 51, 21, 20))
        self.Bt_FtStatus.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:50px;")
        self.Bt_FtStatus.setObjectName("Bt_FtStatus")
        self.verticalLayout_6.addWidget(self.groupBox)
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame_14.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tx_BuscaAtendimento = QtWidgets.QLineEdit(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_BuscaAtendimento.sizePolicy().hasHeightForWidth())
        self.tx_BuscaAtendimento.setSizePolicy(sizePolicy)
        self.tx_BuscaAtendimento.setMaximumSize(QtCore.QSize(777777, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tx_BuscaAtendimento.setFont(font)
        self.tx_BuscaAtendimento.setMouseTracking(False)
        self.tx_BuscaAtendimento.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.tx_BuscaAtendimento.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid blue;\n"
"}")
        self.tx_BuscaAtendimento.setObjectName("tx_BuscaAtendimento")
        self.gridLayout_12.addWidget(self.tx_BuscaAtendimento, 0, 0, 1, 1)
        self.Bt_Cad_Atendimento = QtWidgets.QPushButton(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Cad_Atendimento.sizePolicy().hasHeightForWidth())
        self.Bt_Cad_Atendimento.setSizePolicy(sizePolicy)
        self.Bt_Cad_Atendimento.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Cad_Atendimento.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Cad_Atendimento.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Cad_Atendimento.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/adicionar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Cad_Atendimento.setIcon(icon10)
        self.Bt_Cad_Atendimento.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Cad_Atendimento.setObjectName("Bt_Cad_Atendimento")
        self.gridLayout_12.addWidget(self.Bt_Cad_Atendimento, 0, 2, 1, 1)
        self.Bt_AtualizarAtendimento = QtWidgets.QPushButton(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_AtualizarAtendimento.sizePolicy().hasHeightForWidth())
        self.Bt_AtualizarAtendimento.setSizePolicy(sizePolicy)
        self.Bt_AtualizarAtendimento.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_AtualizarAtendimento.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_AtualizarAtendimento.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_AtualizarAtendimento.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/ATUALIZAR.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_AtualizarAtendimento.setIcon(icon11)
        self.Bt_AtualizarAtendimento.setIconSize(QtCore.QSize(50, 30))
        self.Bt_AtualizarAtendimento.setObjectName("Bt_AtualizarAtendimento")
        self.gridLayout_12.addWidget(self.Bt_AtualizarAtendimento, 0, 3, 1, 1)
        self.Bt_Imprimir_Atendimento = QtWidgets.QPushButton(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Imprimir_Atendimento.sizePolicy().hasHeightForWidth())
        self.Bt_Imprimir_Atendimento.setSizePolicy(sizePolicy)
        self.Bt_Imprimir_Atendimento.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Imprimir_Atendimento.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Imprimir_Atendimento.setStyleSheet("QPushButton {\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Imprimir_Atendimento.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/impressora.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Imprimir_Atendimento.setIcon(icon12)
        self.Bt_Imprimir_Atendimento.setIconSize(QtCore.QSize(30, 30))
        self.Bt_Imprimir_Atendimento.setObjectName("Bt_Imprimir_Atendimento")
        self.gridLayout_12.addWidget(self.Bt_Imprimir_Atendimento, 0, 5, 1, 1)
        self.Bt_Edit_Atendimento = QtWidgets.QPushButton(parent=self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Edit_Atendimento.sizePolicy().hasHeightForWidth())
        self.Bt_Edit_Atendimento.setSizePolicy(sizePolicy)
        self.Bt_Edit_Atendimento.setMinimumSize(QtCore.QSize(0, 0))
        self.Bt_Edit_Atendimento.setMaximumSize(QtCore.QSize(60, 33))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Bt_Edit_Atendimento.setFont(font)
        self.Bt_Edit_Atendimento.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Edit_Atendimento.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Edit_Atendimento.setIcon(icon13)
        self.Bt_Edit_Atendimento.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Edit_Atendimento.setObjectName("Bt_Edit_Atendimento")
        self.gridLayout_12.addWidget(self.Bt_Edit_Atendimento, 0, 4, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_6)
        self.frame_15.setStyleSheet("background-color: rgb(0, 113, 170);")
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_15)
        self.frame_26.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_27.setStyleSheet("background-color: rgb(47, 163, 163);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.Lb_TotalAtendimento = QtWidgets.QPushButton(parent=self.frame_27)
        self.Lb_TotalAtendimento.setGeometry(QtCore.QRect(200, 0, 100, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lb_TotalAtendimento.sizePolicy().hasHeightForWidth())
        self.Lb_TotalAtendimento.setSizePolicy(sizePolicy)
        self.Lb_TotalAtendimento.setMinimumSize(QtCore.QSize(0, 41))
        self.Lb_TotalAtendimento.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Lb_TotalAtendimento.setFont(font)
        self.Lb_TotalAtendimento.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Lb_TotalAtendimento.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Lb_TotalAtendimento.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Lb_TotalAtendimento.setStyleSheet("background-color: rgb(47, 163, 163);\n"
"border:none;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("G:/Meu Drive/PROGRAMAÇÃO/PROJETOS/MEUS PROJETOS/SISTEMA SAÚDE 11.02.2023/interfaces/images.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Lb_TotalAtendimento.setIcon(icon14)
        self.Lb_TotalAtendimento.setIconSize(QtCore.QSize(75, 25))
        self.Lb_TotalAtendimento.setObjectName("Lb_TotalAtendimento")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.frame_27)
        self.lineEdit_2.setGeometry(QtCore.QRect(0, 0, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setStyleSheet("border:none;\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_10.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(parent=self.frame_26)
        self.frame_28.setStyleSheet("background-color: rgb(47, 163, 163);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_10.addWidget(self.frame_28)
        self.gridLayout_6.addWidget(self.frame_26, 1, 0, 1, 1)
        self.TableWidget_Atendimento = QtWidgets.QTableWidget(parent=self.frame_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Atendimento.sizePolicy().hasHeightForWidth())
        self.TableWidget_Atendimento.setSizePolicy(sizePolicy)
        self.TableWidget_Atendimento.setStyleSheet("QHeaderView:section{\n"
"background-color: rgb(0, 113, 170);\n"
"padding: 5px 5px 5px 0px ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 1px solid #CCC;\n"
"}\n"
"QTableView{\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 12px;\n"
"color: rgb(113, 113, 113);\n"
"\n"
"}\n"
"")
        self.TableWidget_Atendimento.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.TableWidget_Atendimento.setDragDropOverwriteMode(True)
        self.TableWidget_Atendimento.setColumnCount(10)
        self.TableWidget_Atendimento.setObjectName("TableWidget_Atendimento")
        self.TableWidget_Atendimento.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Atendimento.setHorizontalHeaderItem(9, item)
        self.TableWidget_Atendimento.horizontalHeader().setDefaultSectionSize(153)
        self.TableWidget_Atendimento.horizontalHeader().setMinimumSectionSize(15)
        self.TableWidget_Atendimento.verticalHeader().setHighlightSections(True)
        self.TableWidget_Atendimento.verticalHeader().setSortIndicatorShown(False)
        self.TableWidget_Atendimento.verticalHeader().setStretchLastSection(False)
        self.gridLayout_6.addWidget(self.TableWidget_Atendimento, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_15)
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.atendimento)
        self.clientes = QtWidgets.QWidget()
        self.clientes.setObjectName("clientes")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.clientes)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.clientes)
        self.frame_4.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_8.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.518552, y1:0.414227, x2:0.52957, y2:1, stop:0 #1CB5E0 , stop:1 #1CB5E0);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_14.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
"\n"
"text-transform: uppercase\n"
" }\n"
"QPushButton:hover{\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"text-decoration:underline;\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_14.setIcon(icon3)
        self.pushButton_14.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_5.addWidget(self.pushButton_14)
        spacerItem6 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame_9.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.tx_BuscaClientes = QtWidgets.QLineEdit(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_BuscaClientes.sizePolicy().hasHeightForWidth())
        self.tx_BuscaClientes.setSizePolicy(sizePolicy)
        self.tx_BuscaClientes.setMaximumSize(QtCore.QSize(777777, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tx_BuscaClientes.setFont(font)
        self.tx_BuscaClientes.setMouseTracking(False)
        self.tx_BuscaClientes.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.tx_BuscaClientes.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid blue;\n"
"}")
        self.tx_BuscaClientes.setObjectName("tx_BuscaClientes")
        self.gridLayout_8.addWidget(self.tx_BuscaClientes, 0, 0, 1, 1)
        self.Bt_Cad_Cliente = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Cad_Cliente.sizePolicy().hasHeightForWidth())
        self.Bt_Cad_Cliente.setSizePolicy(sizePolicy)
        self.Bt_Cad_Cliente.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Cad_Cliente.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Cad_Cliente.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Cad_Cliente.setText("")
        self.Bt_Cad_Cliente.setIcon(icon10)
        self.Bt_Cad_Cliente.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Cad_Cliente.setObjectName("Bt_Cad_Cliente")
        self.gridLayout_8.addWidget(self.Bt_Cad_Cliente, 0, 2, 1, 1)
        self.Bt_Edit_Cliente = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Edit_Cliente.sizePolicy().hasHeightForWidth())
        self.Bt_Edit_Cliente.setSizePolicy(sizePolicy)
        self.Bt_Edit_Cliente.setMinimumSize(QtCore.QSize(0, 0))
        self.Bt_Edit_Cliente.setMaximumSize(QtCore.QSize(60, 33))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Bt_Edit_Cliente.setFont(font)
        self.Bt_Edit_Cliente.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Edit_Cliente.setText("")
        self.Bt_Edit_Cliente.setIcon(icon13)
        self.Bt_Edit_Cliente.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Edit_Cliente.setObjectName("Bt_Edit_Cliente")
        self.gridLayout_8.addWidget(self.Bt_Edit_Cliente, 0, 4, 1, 1)
        self.Bt_Excluir_Cliente = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Excluir_Cliente.sizePolicy().hasHeightForWidth())
        self.Bt_Excluir_Cliente.setSizePolicy(sizePolicy)
        self.Bt_Excluir_Cliente.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Excluir_Cliente.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Excluir_Cliente.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Excluir_Cliente.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/remover.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Excluir_Cliente.setIcon(icon15)
        self.Bt_Excluir_Cliente.setIconSize(QtCore.QSize(30, 27))
        self.Bt_Excluir_Cliente.setObjectName("Bt_Excluir_Cliente")
        self.gridLayout_8.addWidget(self.Bt_Excluir_Cliente, 0, 5, 1, 1)
        self.Bt_Imprimir_Cliente = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Imprimir_Cliente.sizePolicy().hasHeightForWidth())
        self.Bt_Imprimir_Cliente.setSizePolicy(sizePolicy)
        self.Bt_Imprimir_Cliente.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Imprimir_Cliente.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Imprimir_Cliente.setStyleSheet("QPushButton {\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Imprimir_Cliente.setText("")
        self.Bt_Imprimir_Cliente.setIcon(icon12)
        self.Bt_Imprimir_Cliente.setIconSize(QtCore.QSize(30, 30))
        self.Bt_Imprimir_Cliente.setObjectName("Bt_Imprimir_Cliente")
        self.gridLayout_8.addWidget(self.Bt_Imprimir_Cliente, 0, 6, 1, 1)
        self.Bt_PesquisaCliente = QtWidgets.QPushButton(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_PesquisaCliente.sizePolicy().hasHeightForWidth())
        self.Bt_PesquisaCliente.setSizePolicy(sizePolicy)
        self.Bt_PesquisaCliente.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_PesquisaCliente.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_PesquisaCliente.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_PesquisaCliente.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("img/pesquisar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_PesquisaCliente.setIcon(icon16)
        self.Bt_PesquisaCliente.setIconSize(QtCore.QSize(50, 30))
        self.Bt_PesquisaCliente.setObjectName("Bt_PesquisaCliente")
        self.gridLayout_8.addWidget(self.Bt_PesquisaCliente, 0, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_10.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.TableWidget_Cliente = QtWidgets.QTableWidget(parent=self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Cliente.sizePolicy().hasHeightForWidth())
        self.TableWidget_Cliente.setSizePolicy(sizePolicy)
        self.TableWidget_Cliente.setStyleSheet("QHeaderView:section{\n"
"background-color: rgb(0, 113, 170);\n"
"padding: 5px 5px 5px 0px ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 1px solid #CCC;\n"
"}\n"
"QTableView{\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 12px;\n"
"color: rgb(113, 113, 113);\n"
"\n"
"}\n"
"")
        self.TableWidget_Cliente.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.TableWidget_Cliente.setDragDropOverwriteMode(True)
        self.TableWidget_Cliente.setColumnCount(5)
        self.TableWidget_Cliente.setObjectName("TableWidget_Cliente")
        self.TableWidget_Cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Cliente.setHorizontalHeaderItem(4, item)
        self.TableWidget_Cliente.horizontalHeader().setDefaultSectionSize(300)
        self.TableWidget_Cliente.horizontalHeader().setMinimumSectionSize(15)
        self.TableWidget_Cliente.verticalHeader().setHighlightSections(True)
        self.TableWidget_Cliente.verticalHeader().setSortIndicatorShown(False)
        self.TableWidget_Cliente.verticalHeader().setStretchLastSection(False)
        self.gridLayout_7.addWidget(self.TableWidget_Cliente, 0, 0, 1, 1)
        self.frame_29 = QtWidgets.QFrame(parent=self.frame_10)
        self.frame_29.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_29.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_30 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_30.setStyleSheet("background-color: rgb(47, 163, 163);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_30.setObjectName("frame_30")
        self.Lb_Total_Geral_2 = QtWidgets.QPushButton(parent=self.frame_30)
        self.Lb_Total_Geral_2.setGeometry(QtCore.QRect(200, 0, 100, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Lb_Total_Geral_2.sizePolicy().hasHeightForWidth())
        self.Lb_Total_Geral_2.setSizePolicy(sizePolicy)
        self.Lb_Total_Geral_2.setMinimumSize(QtCore.QSize(0, 41))
        self.Lb_Total_Geral_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Lb_Total_Geral_2.setFont(font)
        self.Lb_Total_Geral_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Lb_Total_Geral_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Lb_Total_Geral_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Lb_Total_Geral_2.setStyleSheet("background-color: rgb(47, 163, 163);\n"
"border:none;\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Lb_Total_Geral_2.setIcon(icon14)
        self.Lb_Total_Geral_2.setIconSize(QtCore.QSize(75, 25))
        self.Lb_Total_Geral_2.setObjectName("Lb_Total_Geral_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame_30)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 0, 191, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_3.setSizePolicy(sizePolicy)
        self.lineEdit_3.setStyleSheet("border:none;\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_11.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(parent=self.frame_29)
        self.frame_31.setStyleSheet("background-color: rgb(47, 163, 163);")
        self.frame_31.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_31.setObjectName("frame_31")
        self.horizontalLayout_11.addWidget(self.frame_31)
        self.gridLayout_7.addWidget(self.frame_29, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_10)
        self.gridLayout_2.addWidget(self.frame_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.clientes)
        self.usuarios = QtWidgets.QWidget()
        self.usuarios.setObjectName("usuarios")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.usuarios)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_7 = QtWidgets.QFrame(parent=self.usuarios)
        self.frame_7.setStyleSheet("background-color: rgb(118, 118, 118);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_11.setStyleSheet("background-color: #1CB5E0")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_11)
        self.pushButton_11.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
"\n"
"text-transform: uppercase\n"
" }\n"
"QPushButton:hover{\n"
"background-color:  #1CB5E0;\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"text-decoration:underline;\n"
"\n"
"\n"
"\n"
"}")
        self.pushButton_11.setIcon(icon4)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        spacerItem7 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 33))
        self.frame_12.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.Bt_Edit_Usuario = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Edit_Usuario.sizePolicy().hasHeightForWidth())
        self.Bt_Edit_Usuario.setSizePolicy(sizePolicy)
        self.Bt_Edit_Usuario.setMinimumSize(QtCore.QSize(0, 0))
        self.Bt_Edit_Usuario.setMaximumSize(QtCore.QSize(60, 33))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.Bt_Edit_Usuario.setFont(font)
        self.Bt_Edit_Usuario.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Edit_Usuario.setText("")
        self.Bt_Edit_Usuario.setIcon(icon13)
        self.Bt_Edit_Usuario.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Edit_Usuario.setObjectName("Bt_Edit_Usuario")
        self.gridLayout_9.addWidget(self.Bt_Edit_Usuario, 0, 4, 1, 1)
        self.tx_BuscaUsuarios = QtWidgets.QLineEdit(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_BuscaUsuarios.sizePolicy().hasHeightForWidth())
        self.tx_BuscaUsuarios.setSizePolicy(sizePolicy)
        self.tx_BuscaUsuarios.setMaximumSize(QtCore.QSize(777777, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tx_BuscaUsuarios.setFont(font)
        self.tx_BuscaUsuarios.setMouseTracking(False)
        self.tx_BuscaUsuarios.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.tx_BuscaUsuarios.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase;\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid blue;\n"
"}")
        self.tx_BuscaUsuarios.setObjectName("tx_BuscaUsuarios")
        self.gridLayout_9.addWidget(self.tx_BuscaUsuarios, 0, 0, 1, 1)
        self.Bt_Remover_Usuario = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Remover_Usuario.sizePolicy().hasHeightForWidth())
        self.Bt_Remover_Usuario.setSizePolicy(sizePolicy)
        self.Bt_Remover_Usuario.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Remover_Usuario.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Remover_Usuario.setStyleSheet("QPushButton {\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Remover_Usuario.setText("")
        self.Bt_Remover_Usuario.setIcon(icon15)
        self.Bt_Remover_Usuario.setIconSize(QtCore.QSize(30, 27))
        self.Bt_Remover_Usuario.setObjectName("Bt_Remover_Usuario")
        self.gridLayout_9.addWidget(self.Bt_Remover_Usuario, 0, 5, 1, 1)
        self.Bt_Add_Usuario = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Add_Usuario.sizePolicy().hasHeightForWidth())
        self.Bt_Add_Usuario.setSizePolicy(sizePolicy)
        self.Bt_Add_Usuario.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Add_Usuario.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Add_Usuario.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Add_Usuario.setText("")
        self.Bt_Add_Usuario.setIcon(icon10)
        self.Bt_Add_Usuario.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Add_Usuario.setObjectName("Bt_Add_Usuario")
        self.gridLayout_9.addWidget(self.Bt_Add_Usuario, 0, 2, 1, 1)
        self.Bt_Pesquisa_Usuario = QtWidgets.QPushButton(parent=self.frame_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Bt_Pesquisa_Usuario.sizePolicy().hasHeightForWidth())
        self.Bt_Pesquisa_Usuario.setSizePolicy(sizePolicy)
        self.Bt_Pesquisa_Usuario.setMinimumSize(QtCore.QSize(0, 33))
        self.Bt_Pesquisa_Usuario.setMaximumSize(QtCore.QSize(50, 16777215))
        self.Bt_Pesquisa_Usuario.setStyleSheet("QPushButton {\n"
"\n"
"background-color: rgb(229, 229, 229);\n"
"border:none;\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.Bt_Pesquisa_Usuario.setText("")
        self.Bt_Pesquisa_Usuario.setIcon(icon16)
        self.Bt_Pesquisa_Usuario.setIconSize(QtCore.QSize(50, 30))
        self.Bt_Pesquisa_Usuario.setObjectName("Bt_Pesquisa_Usuario")
        self.gridLayout_9.addWidget(self.Bt_Pesquisa_Usuario, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_12)
        self.frame_16 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_16.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TableWidget_Usuario = QtWidgets.QTableWidget(parent=self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TableWidget_Usuario.sizePolicy().hasHeightForWidth())
        self.TableWidget_Usuario.setSizePolicy(sizePolicy)
        self.TableWidget_Usuario.setStyleSheet("QHeaderView:section{\n"
"background-color: rgb(0, 113, 170);\n"
"padding: 5px 5px 5px 0px ;\n"
"font-size: 12px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"color: rgb(255, 255, 255);\n"
"border:none;\n"
"border-bottom: 1px solid #CCC;\n"
"}\n"
"QTableView{\n"
"background-color: rgb(255, 255, 255);\n"
"font-size: 12px;\n"
"color: rgb(113, 113, 113);\n"
"\n"
"}\n"
"")
        self.TableWidget_Usuario.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.TableWidget_Usuario.setDragDropOverwriteMode(True)
        self.TableWidget_Usuario.setColumnCount(5)
        self.TableWidget_Usuario.setObjectName("TableWidget_Usuario")
        self.TableWidget_Usuario.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Usuario.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Usuario.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Usuario.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Usuario.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget_Usuario.setHorizontalHeaderItem(4, item)
        self.TableWidget_Usuario.horizontalHeader().setDefaultSectionSize(251)
        self.TableWidget_Usuario.horizontalHeader().setMinimumSectionSize(15)
        self.TableWidget_Usuario.verticalHeader().setHighlightSections(True)
        self.TableWidget_Usuario.verticalHeader().setSortIndicatorShown(False)
        self.TableWidget_Usuario.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.TableWidget_Usuario)
        self.verticalLayout_2.addWidget(self.frame_16)
        self.gridLayout_5.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.usuarios)
        self.suporte = QtWidgets.QWidget()
        self.suporte.setObjectName("suporte")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.suporte)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_66 = QtWidgets.QFrame(parent=self.suporte)
        self.frame_66.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_66.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_66.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_66.setObjectName("frame_66")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.frame_66)
        self.gridLayout_36.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_36.setSpacing(0)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.frame_106 = QtWidgets.QFrame(parent=self.frame_66)
        self.frame_106.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_106.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_106.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_106.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_106.setObjectName("frame_106")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_106)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.frame_106)
        self.pushButton_28.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(213, 213, 213);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"}")
        self.pushButton_28.setIcon(icon5)
        self.pushButton_28.setIconSize(QtCore.QSize(60, 30))
        self.pushButton_28.setObjectName("pushButton_28")
        self.horizontalLayout_34.addWidget(self.pushButton_28)
        spacerItem8 = QtWidgets.QSpacerItem(485, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem8)
        self.gridLayout_36.addWidget(self.frame_106, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.frame_66)
        self.frame_2 = QtWidgets.QFrame(parent=self.suporte)
        self.frame_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_37.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_37.setSpacing(0)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.frame_114 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_114.setMaximumSize(QtCore.QSize(327, 16777215))
        self.frame_114.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_114.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_114.setObjectName("frame_114")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_114)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame_120 = QtWidgets.QFrame(parent=self.frame_114)
        self.frame_120.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_120.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_120.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_120.setObjectName("frame_120")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.frame_120)
        self.gridLayout_48.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_48.setSpacing(0)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.pushButton_30 = QtWidgets.QPushButton(parent=self.frame_120)
        self.pushButton_30.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_30.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(213, 213, 213);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"}")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("img/anydesk_icon_146231.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_30.setIcon(icon17)
        self.pushButton_30.setIconSize(QtCore.QSize(60, 30))
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_48.addWidget(self.pushButton_30, 0, 0, 1, 1)
        self.verticalLayout_31.addWidget(self.frame_120)
        self.frame_121 = QtWidgets.QFrame(parent=self.frame_114)
        self.frame_121.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_121.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_121.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_121.setObjectName("frame_121")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.frame_121)
        self.gridLayout_49.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_49.setSpacing(0)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.Bt_Whatsapp_2 = QtWidgets.QPushButton(parent=self.frame_121)
        self.Bt_Whatsapp_2.setMinimumSize(QtCore.QSize(150, 45))
        self.Bt_Whatsapp_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Bt_Whatsapp_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(213, 213, 213);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"}")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("img/Whatsapp_37229.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Whatsapp_2.setIcon(icon18)
        self.Bt_Whatsapp_2.setIconSize(QtCore.QSize(60, 30))
        self.Bt_Whatsapp_2.setObjectName("Bt_Whatsapp_2")
        self.gridLayout_49.addWidget(self.Bt_Whatsapp_2, 0, 0, 1, 1)
        self.verticalLayout_31.addWidget(self.frame_121)
        self.frame_122 = QtWidgets.QFrame(parent=self.frame_114)
        self.frame_122.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_122.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_122.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_122.setObjectName("frame_122")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.frame_122)
        self.gridLayout_52.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_52.setSpacing(0)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.pushButton_34 = QtWidgets.QPushButton(parent=self.frame_122)
        self.pushButton_34.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_34.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_34.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"\n"
" }\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 170, 255);\n"
"border: none;\n"
"color: rgb(213, 213, 213);\n"
"font-weight: bold;\n"
"font-size: 15px;\n"
"}")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("img/gmail_new_logo_icon_159149.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_34.setIcon(icon19)
        self.pushButton_34.setIconSize(QtCore.QSize(60, 30))
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_52.addWidget(self.pushButton_34, 0, 0, 1, 1)
        self.verticalLayout_31.addWidget(self.frame_122)
        self.gridLayout_37.addWidget(self.frame_114, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.frame_2)
        self.frame_67 = QtWidgets.QFrame(parent=self.suporte)
        self.frame_67.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_67.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_67.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_67.setObjectName("frame_67")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.frame_67)
        self.gridLayout_38.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_38.setSpacing(0)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_67)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 250))
        self.label_25.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.label_25.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("../SISTEMA-SAUDE/img/Banner_LC.png"))
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_38.addWidget(self.label_25, 0, 0, 1, 1)
        self.frame_115 = QtWidgets.QFrame(parent=self.frame_67)
        self.frame_115.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_115.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_115.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_115.setObjectName("frame_115")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.frame_115)
        self.gridLayout_54.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_54.setSpacing(0)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_115)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_54.addWidget(self.label_27, 0, 0, 1, 1)
        self.gridLayout_38.addWidget(self.frame_115, 1, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.frame_67)
        self.frame_68 = QtWidgets.QFrame(parent=self.suporte)
        self.frame_68.setMaximumSize(QtCore.QSize(16777215, 28))
        self.frame_68.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_68.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_68.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_68.setObjectName("frame_68")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.frame_68)
        self.gridLayout_40.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_40.setSpacing(0)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.frame_108 = QtWidgets.QFrame(parent=self.frame_68)
        self.frame_108.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_108.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_108.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_108.setObjectName("frame_108")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_108)
        self.gridLayout_39.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_39.setSpacing(0)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.frame_109 = QtWidgets.QFrame(parent=self.frame_108)
        self.frame_109.setMaximumSize(QtCore.QSize(16777215, 37))
        self.frame_109.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_109.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_109.setObjectName("frame_109")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_109)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem9 = QtWidgets.QSpacerItem(386, 12, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.label_26 = QtWidgets.QLabel(parent=self.frame_109)
        self.label_26.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_16.addWidget(self.label_26)
        spacerItem10 = QtWidgets.QSpacerItem(386, 12, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.gridLayout_39.addWidget(self.frame_109, 0, 0, 1, 1)
        self.gridLayout_40.addWidget(self.frame_108, 0, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.frame_68)
        self.stackedWidget.addWidget(self.suporte)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout_35.addWidget(self.frame_3, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        Form_Inicio.setCentralWidget(self.centralwidget)

        self.retranslateUi(Form_Inicio)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form_Inicio)

    def retranslateUi(self, Form_Inicio):
        _translate = QtCore.QCoreApplication.translate
        Form_Inicio.setWindowTitle(_translate("Form_Inicio", "LC SISTEMAS"))
        self.Bt_Inicio.setToolTip(_translate("Form_Inicio", "Tela Inicio"))
        self.Bt_Atendimento.setToolTip(_translate("Form_Inicio", "<html><head/><body><p>Tela de Controle de Usuários</p></body></html>"))
        self.Bt_Clientes.setToolTip(_translate("Form_Inicio", "<html><head/><body><p>Tela de Cadastro e Informações de Pacientes</p></body></html>"))
        self.Bt_Usuarios.setToolTip(_translate("Form_Inicio", "Tela de Suporte"))
        self.Bt_Suporte.setToolTip(_translate("Form_Inicio", "Tela de Suporte"))
        self.Bt_Sair.setToolTip(_translate("Form_Inicio", "<html><head/><body><p>Sair do Sistema</p></body></html>"))
        self.label_23.setText(_translate("Form_Inicio", "Versão 1.0.0"))
        self.nome_user_3.setText(_translate("Form_Inicio", "Qtd. de cadastro no dia:"))
        self.Lb_User_Logado_3.setText(_translate("Form_Inicio", "55"))
        self.Bt_Expandir.setToolTip(_translate("Form_Inicio", "Inicio"))
        self.Bt_Notifica.setToolTip(_translate("Form_Inicio", "Inicio"))
        self.Bt_Conta_notificacao.setToolTip(_translate("Form_Inicio", "Inicio"))
        self.nome_user_2.setText(_translate("Form_Inicio", "Agendamentos no dia:"))
        self.Lb_User_Logado_2.setText(_translate("Form_Inicio", "55"))
        self.label.setText(_translate("Form_Inicio", "USUÁRIO:"))
        self.label_2.setText(_translate("Form_Inicio", "Todos os direitos reservados © Lucas Costa"))
        self.pushButton_15.setText(_translate("Form_Inicio", "ATENDIMENTO"))
        self.groupBox.setTitle(_translate("Form_Inicio", "FILTROS"))
        self.Lb_FiltroData.setText(_translate("Form_Inicio", "DATA"))
        self.label_5.setText(_translate("Form_Inicio", "STATUS"))
        self.Tx_FiltroStatus.setItemText(0, _translate("Form_Inicio", "SELECIONE"))
        self.Tx_FiltroStatus.setItemText(1, _translate("Form_Inicio", "CONCLUÍDO"))
        self.Tx_FiltroStatus.setItemText(2, _translate("Form_Inicio", "AGUARDANDO"))
        self.Tx_FiltroStatus.setItemText(3, _translate("Form_Inicio", "EM ANDAMENTO"))
        self.Tx_FiltroStatus.setItemText(4, _translate("Form_Inicio", "CANCELADO"))
        self.Bt_FtData.setText(_translate("Form_Inicio", "OK"))
        self.Bt_FtStatus.setText(_translate("Form_Inicio", "OK"))
        self.tx_BuscaAtendimento.setPlaceholderText(_translate("Form_Inicio", "PESQUISAR..."))
        self.Bt_Cad_Atendimento.setToolTip(_translate("Form_Inicio", "Adicionar"))
        self.Bt_AtualizarAtendimento.setToolTip(_translate("Form_Inicio", "Pesquisar"))
        self.Bt_Imprimir_Atendimento.setToolTip(_translate("Form_Inicio", "Imprimir"))
        self.Bt_Edit_Atendimento.setToolTip(_translate("Form_Inicio", "Editar"))
        self.Lb_TotalAtendimento.setText(_translate("Form_Inicio", "0"))
        self.lineEdit_2.setText(_translate("Form_Inicio", "Total de atendimento"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(0)
        item.setText(_translate("Form_Inicio", "ID"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(1)
        item.setText(_translate("Form_Inicio", "STATUS"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(2)
        item.setText(_translate("Form_Inicio", "NOME"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(3)
        item.setText(_translate("Form_Inicio", "CPF"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(4)
        item.setText(_translate("Form_Inicio", "TELEFONE"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(5)
        item.setText(_translate("Form_Inicio", "ENDEREÇO"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(6)
        item.setText(_translate("Form_Inicio", "DEPARTAMENTO"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(7)
        item.setText(_translate("Form_Inicio", "ASSUNTO"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(8)
        item.setText(_translate("Form_Inicio", "OBSERVAÇÃO"))
        item = self.TableWidget_Atendimento.horizontalHeaderItem(9)
        item.setText(_translate("Form_Inicio", "DATA"))
        self.pushButton_14.setText(_translate("Form_Inicio", "CLIENTES"))
        self.tx_BuscaClientes.setPlaceholderText(_translate("Form_Inicio", "PESQUISAR..."))
        self.Bt_Cad_Cliente.setToolTip(_translate("Form_Inicio", "Adicionar"))
        self.Bt_Edit_Cliente.setToolTip(_translate("Form_Inicio", "Editar"))
        self.Bt_Excluir_Cliente.setToolTip(_translate("Form_Inicio", "Excluir"))
        self.Bt_Imprimir_Cliente.setToolTip(_translate("Form_Inicio", "Imprimir"))
        self.Bt_PesquisaCliente.setToolTip(_translate("Form_Inicio", "Pesquisar"))
        item = self.TableWidget_Cliente.horizontalHeaderItem(0)
        item.setText(_translate("Form_Inicio", "ID"))
        item = self.TableWidget_Cliente.horizontalHeaderItem(1)
        item.setText(_translate("Form_Inicio", "NOME"))
        item = self.TableWidget_Cliente.horizontalHeaderItem(2)
        item.setText(_translate("Form_Inicio", "CPF"))
        item = self.TableWidget_Cliente.horizontalHeaderItem(3)
        item.setText(_translate("Form_Inicio", "TELEFONE"))
        item = self.TableWidget_Cliente.horizontalHeaderItem(4)
        item.setText(_translate("Form_Inicio", "ENDEREÇO"))
        self.Lb_Total_Geral_2.setText(_translate("Form_Inicio", "0"))
        self.lineEdit_3.setText(_translate("Form_Inicio", "Total de clientes"))
        self.pushButton_11.setText(_translate("Form_Inicio", "USUÁRIOS"))
        self.Bt_Edit_Usuario.setToolTip(_translate("Form_Inicio", "Editar"))
        self.tx_BuscaUsuarios.setPlaceholderText(_translate("Form_Inicio", "PESQUISAR..."))
        self.Bt_Remover_Usuario.setToolTip(_translate("Form_Inicio", "Excluir"))
        self.Bt_Add_Usuario.setToolTip(_translate("Form_Inicio", "Adicionar"))
        self.Bt_Pesquisa_Usuario.setToolTip(_translate("Form_Inicio", "Pesquisar"))
        item = self.TableWidget_Usuario.horizontalHeaderItem(0)
        item.setText(_translate("Form_Inicio", "ID"))
        item = self.TableWidget_Usuario.horizontalHeaderItem(1)
        item.setText(_translate("Form_Inicio", "NOME COMPLETO"))
        item = self.TableWidget_Usuario.horizontalHeaderItem(2)
        item.setText(_translate("Form_Inicio", "NOME DE USUÁRIO"))
        item = self.TableWidget_Usuario.horizontalHeaderItem(3)
        item.setText(_translate("Form_Inicio", "NÍVEL DE ACESSO"))
        item = self.TableWidget_Usuario.horizontalHeaderItem(4)
        item.setText(_translate("Form_Inicio", "PERMISSÕES"))
        self.pushButton_28.setText(_translate("Form_Inicio", "SUPORTE"))
        self.pushButton_30.setText(_translate("Form_Inicio", "Suporte Remoto"))
        self.Bt_Whatsapp_2.setText(_translate("Form_Inicio", "(66) 98412-4977"))
        self.pushButton_34.setText(_translate("Form_Inicio", "lcinformaticastz@gmail.com"))
        self.label_26.setText(_translate("Form_Inicio", "Todos os direitos reservados © LC INFORMÁTICA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Inicio = QtWidgets.QMainWindow()
    ui = Ui_Form_Inicio()
    ui.setupUi(Form_Inicio)
    Form_Inicio.show()
    sys.exit(app.exec())
