# Form implementation generated from reading ui file 'Form_Editar_Atendimento.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_EditAtendimento(object):
    def setupUi(self, Form_EditAtendimento):
        Form_EditAtendimento.setObjectName("Form_EditAtendimento")
        Form_EditAtendimento.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Form_EditAtendimento.resize(1000, 500)
        Form_EditAtendimento.setMinimumSize(QtCore.QSize(1000, 500))
        Form_EditAtendimento.setMaximumSize(QtCore.QSize(1000, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/produtos-.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form_EditAtendimento.setWindowIcon(icon)
        self.fr_FormProdutos = QtWidgets.QFrame(parent=Form_EditAtendimento)
        self.fr_FormProdutos.setGeometry(QtCore.QRect(0, 0, 1000, 500))
        self.fr_FormProdutos.setStyleSheet("background: #FFF;\n"
"border: none")
        self.fr_FormProdutos.setObjectName("fr_FormProdutos")
        self.lb_FormProdutos = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormProdutos.setGeometry(QtCore.QRect(410, 10, 491, 30))
        self.lb_FormProdutos.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;\n"
"\n"
"border-bottom: 2px solid #A2A2A2\n"
"}")
        self.lb_FormProdutos.setObjectName("lb_FormProdutos")
        self.lb_FotoLogo = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FotoLogo.setGeometry(QtCore.QRect(20, 40, 301, 411))
        self.lb_FotoLogo.setStyleSheet("border: 1px solid #A2A2A2;\n"
"background: url(\'Images/icon/Photo.svg\') center no-repeat \n"
"")
        self.lb_FotoLogo.setText("")
        self.lb_FotoLogo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lb_FotoLogo.setObjectName("lb_FotoLogo")
        self.lb_FormNome = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormNome.setGeometry(QtCore.QRect(410, 60, 150, 20))
        self.lb_FormNome.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormNome.setObjectName("lb_FormNome")
        self.tx_Nome = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Nome.setGeometry(QtCore.QRect(410, 85, 501, 25))
        self.tx_Nome.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Nome.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Nome.setClearButtonEnabled(True)
        self.tx_Nome.setObjectName("tx_Nome")
        self.lb_FormCpf = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormCpf.setGeometry(QtCore.QRect(410, 120, 215, 20))
        self.lb_FormCpf.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormCpf.setObjectName("lb_FormCpf")
        self.cb_Departamento = QtWidgets.QComboBox(parent=self.fr_FormProdutos)
        self.cb_Departamento.setGeometry(QtCore.QRect(410, 330, 211, 25))
        self.cb_Departamento.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_Departamento.setObjectName("cb_Departamento")
        self.cb_Departamento.addItem("")
        self.cb_Departamento.addItem("")
        self.lb_FormTelefone = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormTelefone.setGeometry(QtCore.QRect(720, 120, 191, 20))
        self.lb_FormTelefone.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormTelefone.setObjectName("lb_FormTelefone")
        self.lb_FormEndereco = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormEndereco.setGeometry(QtCore.QRect(410, 190, 215, 20))
        self.lb_FormEndereco.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormEndereco.setObjectName("lb_FormEndereco")
        self.tx_Cpf = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Cpf.setGeometry(QtCore.QRect(410, 150, 215, 25))
        self.tx_Cpf.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Cpf.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Cpf.setPlaceholderText("")
        self.tx_Cpf.setClearButtonEnabled(True)
        self.tx_Cpf.setObjectName("tx_Cpf")
        self.tx_Telefone = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Telefone.setGeometry(QtCore.QRect(720, 150, 191, 25))
        self.tx_Telefone.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Telefone.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" \n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Telefone.setPlaceholderText("")
        self.tx_Telefone.setClearButtonEnabled(True)
        self.tx_Telefone.setObjectName("tx_Telefone")
        self.lb_Form_Atendimento = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_Form_Atendimento.setGeometry(QtCore.QRect(410, 270, 461, 21))
        self.lb_Form_Atendimento.setStyleSheet("QLabel{\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: normal;\n"
"\n"
"border-bottom: 2px solid #A2A2A2;\n"
"color: #797979\n"
"}")
        self.lb_Form_Atendimento.setObjectName("lb_Form_Atendimento")
        self.lb_FormDepartamento = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormDepartamento.setGeometry(QtCore.QRect(410, 300, 101, 20))
        self.lb_FormDepartamento.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormDepartamento.setObjectName("lb_FormDepartamento")
        self.fr_BotoesFormProdutos = QtWidgets.QFrame(parent=self.fr_FormProdutos)
        self.fr_BotoesFormProdutos.setGeometry(QtCore.QRect(0, 470, 1000, 30))
        self.fr_BotoesFormProdutos.setStyleSheet("background:#E1DFE0;\n"
"border: none;")
        self.fr_BotoesFormProdutos.setObjectName("fr_BotoesFormProdutos")
        self.Bt_Can_Agendamento = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_Can_Agendamento.setGeometry(QtCore.QRect(880, 0, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Can_Agendamento.setFont(font)
        self.Bt_Can_Agendamento.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Can_Agendamento.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Can_Agendamento.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Can_Agendamento.setStyleSheet("QPushButton {\n"
"background-color: #1E87F0;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/sair/delete_delete_exit_1577.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Can_Agendamento.setIcon(icon1)
        self.Bt_Can_Agendamento.setIconSize(QtCore.QSize(75, 25))
        self.Bt_Can_Agendamento.setObjectName("Bt_Can_Agendamento")
        self.Bt_Salvar_agendamento = QtWidgets.QPushButton(parent=self.fr_BotoesFormProdutos)
        self.Bt_Salvar_agendamento.setGeometry(QtCore.QRect(750, 0, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Bt_Salvar_agendamento.setFont(font)
        self.Bt_Salvar_agendamento.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Bt_Salvar_agendamento.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.Bt_Salvar_agendamento.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.Bt_Salvar_agendamento.setStyleSheet("QPushButton {\n"
"background-color: #7AB32E;\n"
"color: #FFF\n"
" }\n"
"QPushButton:hover{\n"
"background-color: #40a286\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/salvar/salvar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Bt_Salvar_agendamento.setIcon(icon2)
        self.Bt_Salvar_agendamento.setIconSize(QtCore.QSize(50, 25))
        self.Bt_Salvar_agendamento.setObjectName("Bt_Salvar_agendamento")
        self.lb_qtdeMin = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_qtdeMin.setGeometry(QtCore.QRect(590, 330, 31, 25))
        self.lb_qtdeMin.setStyleSheet("background: #7AB32E;\n"
"color: #FFF")
        self.lb_qtdeMin.setText("")
        self.lb_qtdeMin.setObjectName("lb_qtdeMin")
        self.tx_Endereco = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Endereco.setGeometry(QtCore.QRect(410, 220, 211, 25))
        self.tx_Endereco.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Endereco.setClearButtonEnabled(True)
        self.tx_Endereco.setObjectName("tx_Endereco")
        self.lb_FormAssunto = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormAssunto.setGeometry(QtCore.QRect(660, 300, 101, 20))
        self.lb_FormAssunto.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormAssunto.setObjectName("lb_FormAssunto")
        self.tx_Assunto = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Assunto.setGeometry(QtCore.QRect(660, 330, 251, 25))
        self.tx_Assunto.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Assunto.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Assunto.setClearButtonEnabled(True)
        self.tx_Assunto.setObjectName("tx_Assunto")
        self.tx_Observacao = QtWidgets.QLineEdit(parent=self.fr_FormProdutos)
        self.tx_Observacao.setGeometry(QtCore.QRect(410, 400, 501, 61))
        self.tx_Observacao.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.tx_Observacao.setStyleSheet("QLineEdit{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"\n"
"}\n"
"QLineEdit:Focus {\n"
"border: 1px solid red;\n"
"}")
        self.tx_Observacao.setClearButtonEnabled(True)
        self.tx_Observacao.setObjectName("tx_Observacao")
        self.lb_FormObservacao = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormObservacao.setGeometry(QtCore.QRect(410, 370, 101, 20))
        self.lb_FormObservacao.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormObservacao.setObjectName("lb_FormObservacao")
        self.lb_qtdeMin_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_qtdeMin_2.setGeometry(QtCore.QRect(290, 420, 31, 31))
        self.lb_qtdeMin_2.setStyleSheet("background: #7AB32E;\n"
"color: #FFF")
        self.lb_qtdeMin_2.setText("")
        self.lb_qtdeMin_2.setObjectName("lb_qtdeMin_2")
        self.label = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.label.setGeometry(QtCore.QRect(20, 40, 301, 31))
        self.label.setStyleSheet("background: #CFCFCF;\n"
"border: 1px solid #A2A2A2;\n"
"color: #000;\n"
"font-size: 14px;\n"
"font-family: \"Arial\";\n"
"font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.cb_StatusAtendimento = QtWidgets.QComboBox(parent=self.fr_FormProdutos)
        self.cb_StatusAtendimento.setGeometry(QtCore.QRect(720, 220, 191, 25))
        self.cb_StatusAtendimento.setStyleSheet("QComboBox{\n"
"background: #CFCFCF;\n"
"border-radius: 2px;\n"
"color: #000;\n"
"font: 13px \"Arial\" ;\n"
"text-transform: uppercase\n"
"}\n"
"QComboBox:Focus {\n"
"border: 1px solid red;\n"
"}\n"
" QComboBox::drop-down {\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 25px;\n"
"     border-left-width: 1px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"QComboBox::down-arrow {\n"
"     image: url(\"+self.resourcepath(\'Images/down.png\')+\");\n"
" }\n"
"")
        self.cb_StatusAtendimento.setObjectName("cb_StatusAtendimento")
        self.cb_StatusAtendimento.addItem("")
        self.cb_StatusAtendimento.addItem("")
        self.cb_StatusAtendimento.addItem("")
        self.cb_StatusAtendimento.addItem("")
        self.cb_StatusAtendimento.addItem("")
        self.lb_FormDepartamento_2 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_FormDepartamento_2.setGeometry(QtCore.QRect(720, 190, 101, 20))
        self.lb_FormDepartamento_2.setStyleSheet("QLabel{\n"
"font-size: 12px;\n"
"font-family: \"Arial Unicode MS\";\n"
"font-weight: bold;\n"
"color: #797979\n"
"}")
        self.lb_FormDepartamento_2.setObjectName("lb_FormDepartamento_2")
        self.lb_qtdeMin_3 = QtWidgets.QLabel(parent=self.fr_FormProdutos)
        self.lb_qtdeMin_3.setGeometry(QtCore.QRect(880, 220, 31, 25))
        self.lb_qtdeMin_3.setStyleSheet("background: #7AB32E;\n"
"color: #FFF")
        self.lb_qtdeMin_3.setText("")
        self.lb_qtdeMin_3.setObjectName("lb_qtdeMin_3")
        self.tx_Endereco.raise_()
        self.lb_FormProdutos.raise_()
        self.lb_FotoLogo.raise_()
        self.lb_FormNome.raise_()
        self.tx_Nome.raise_()
        self.lb_FormCpf.raise_()
        self.cb_Departamento.raise_()
        self.lb_FormTelefone.raise_()
        self.lb_FormEndereco.raise_()
        self.tx_Cpf.raise_()
        self.tx_Telefone.raise_()
        self.lb_Form_Atendimento.raise_()
        self.lb_FormDepartamento.raise_()
        self.fr_BotoesFormProdutos.raise_()
        self.lb_qtdeMin.raise_()
        self.lb_FormAssunto.raise_()
        self.tx_Assunto.raise_()
        self.tx_Observacao.raise_()
        self.lb_FormObservacao.raise_()
        self.lb_qtdeMin_2.raise_()
        self.label.raise_()
        self.cb_StatusAtendimento.raise_()
        self.lb_FormDepartamento_2.raise_()
        self.lb_qtdeMin_3.raise_()

        self.retranslateUi(Form_EditAtendimento)
        QtCore.QMetaObject.connectSlotsByName(Form_EditAtendimento)
        Form_EditAtendimento.setTabOrder(self.tx_Nome, self.tx_Cpf)
        Form_EditAtendimento.setTabOrder(self.tx_Cpf, self.tx_Telefone)
        Form_EditAtendimento.setTabOrder(self.tx_Telefone, self.tx_Endereco)
        Form_EditAtendimento.setTabOrder(self.tx_Endereco, self.cb_Departamento)
        Form_EditAtendimento.setTabOrder(self.cb_Departamento, self.tx_Assunto)
        Form_EditAtendimento.setTabOrder(self.tx_Assunto, self.tx_Observacao)

    def retranslateUi(self, Form_EditAtendimento):
        _translate = QtCore.QCoreApplication.translate
        Form_EditAtendimento.setWindowTitle(_translate("Form_EditAtendimento", "LC INFORMÁTICA | CADASTRO ATENDIMENTO"))
        self.lb_FormProdutos.setText(_translate("Form_EditAtendimento", "CADASTRAR ATENDIMENTO"))
        self.lb_FotoLogo.setToolTip(_translate("Form_EditAtendimento", "Insira uma imagem"))
        self.lb_FormNome.setText(_translate("Form_EditAtendimento", "NOME"))
        self.tx_Nome.setPlaceholderText(_translate("Form_EditAtendimento", "Nome  completo"))
        self.lb_FormCpf.setText(_translate("Form_EditAtendimento", "CPF"))
        self.cb_Departamento.setItemText(0, _translate("Form_EditAtendimento", "SELECIONE"))
        self.cb_Departamento.setItemText(1, _translate("Form_EditAtendimento", "GABINETE"))
        self.lb_FormTelefone.setText(_translate("Form_EditAtendimento", "TELEFONE"))
        self.lb_FormEndereco.setText(_translate("Form_EditAtendimento", "ENDEREÇO"))
        self.tx_Cpf.setInputMask(_translate("Form_EditAtendimento", "000.000.000-00"))
        self.tx_Cpf.setText(_translate("Form_EditAtendimento", "..-"))
        self.tx_Telefone.setInputMask(_translate("Form_EditAtendimento", "(00) 00000-0000"))
        self.tx_Telefone.setText(_translate("Form_EditAtendimento", "() -"))
        self.lb_Form_Atendimento.setText(_translate("Form_EditAtendimento", "ATENDIMENTO"))
        self.lb_FormDepartamento.setText(_translate("Form_EditAtendimento", "DEPARTAMENTO"))
        self.Bt_Can_Agendamento.setText(_translate("Form_EditAtendimento", "CANCELAR"))
        self.Bt_Salvar_agendamento.setText(_translate("Form_EditAtendimento", "SALVAR"))
        self.tx_Endereco.setPlaceholderText(_translate("Form_EditAtendimento", "Endereço ou localidade"))
        self.lb_FormAssunto.setText(_translate("Form_EditAtendimento", "ASSUNTO"))
        self.tx_Assunto.setPlaceholderText(_translate("Form_EditAtendimento", "Opcional"))
        self.tx_Observacao.setPlaceholderText(_translate("Form_EditAtendimento", "Opcional"))
        self.lb_FormObservacao.setText(_translate("Form_EditAtendimento", "OBSERVAÇÃO"))
        self.label.setText(_translate("Form_EditAtendimento", "Prefeitura municipal de santa terezinha"))
        self.cb_StatusAtendimento.setItemText(0, _translate("Form_EditAtendimento", "SELECIONE"))
        self.cb_StatusAtendimento.setItemText(1, _translate("Form_EditAtendimento", "AGUARDANDO"))
        self.cb_StatusAtendimento.setItemText(2, _translate("Form_EditAtendimento", "EM ANDAMENTO"))
        self.cb_StatusAtendimento.setItemText(3, _translate("Form_EditAtendimento", "CONCLUÍDO"))
        self.cb_StatusAtendimento.setItemText(4, _translate("Form_EditAtendimento", "CANCELADO"))
        self.lb_FormDepartamento_2.setText(_translate("Form_EditAtendimento", "STATUS"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_EditAtendimento = QtWidgets.QFrame()
    ui = Ui_Form_EditAtendimento()
    ui.setupUi(Form_EditAtendimento)
    Form_EditAtendimento.show()
    sys.exit(app.exec())
